site_name: EKS Cluster w/ Secondary CIDR and Karpenter
repo_url: https://github.com/oguzhan-yilmaz/karpenter-eks-vpc-secondary-cidr
repo_name: oguzhan-yilmaz/karpenter-eks-vpc-secondary-cidr

nav:
  - Home: README.md
  - "Karpenter v1beta(v0.32+)": karpenter-v1beta-configuration.md
  - "Migrate from AWSNodeTemplate to NodeClass (a.k.a. v1beta1 Migration)": migrate-from-awsnodetemplate-to-nodeclass.md
  - "Multi NodeClass Strategy": multi-nodeclass-strategy.md
  - "Full Demo":
    - "0. About the Demo": eksdemo-secondary-cidr-and-cni-custom-netwoking/README.md
    - "1. Create VPC with Secondary CIDR and Subnets": eksdemo-secondary-cidr-and-cni-custom-netwoking/1-vpc-secondary-cidr-and-subnets.md
    - "2. AWS VPC CNI & ENIConfig configuration for Custom Networking": eksdemo-secondary-cidr-and-cni-custom-netwoking/2-aws-vpc-cni-configuration.md
    - "3. Karpenter v1alpha Configuration": eksdemo-secondary-cidr-and-cni-custom-netwoking/3-karpenter-v1alpha-configuration.md
    - "Demo Troubleshooting": eksdemo-secondary-cidr-and-cni-custom-netwoking/troubleshooting.md
    - "Create Load on the Cluster": eksdemo-secondary-cidr-and-cni-custom-netwoking/create-load-on-the-cluster.md
  - "ec2-instance-selector CLI tool": ec2-instance-selector.md
  
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  

  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.png
  features:
    - navigation.tracking
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oguzhan-yilmaz
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/oguzhan-y/
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/oguzhan_y_

markdown_extensions:
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - mkdocstrings
  - autorefs