apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "foobar"
  region: eu-central-1

nodeGroups:
  - name: new-subnet-nodegroup
    instanceType: m5.large
    desiredCapacity: 1
    privateNetworking: true
    subnets:
      - "subnet-0af9794264f7165bc"
      - "subnet-0b974d5872910ab7b"
      - "subnet-00782ed1060ae5f88"
